version: '3'
services:
#mssql docker
  ecinema-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - ecinemanet2022

  ecinema-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=ecinema-sql,1433;Database=eCinema;User=sa;Password=QWElkj132!;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5192:5192
    networks:
      - ecinemanet2022
    links:
      - ecinema-sql
    depends_on:
      - ecinema-sql
      
networks:
  ecinemanet2022:
    driver: bridge 